#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if echo "$branch" | grep -Eq "^main$|^develop$|^release"; then
  echo "🚫 Você não pode commitar direto na branch '$branch'."
  echo "👉 Crie uma branch do tipo: feature/, hotfix/, chore/, etc."
  exit 1
fi
